Add lsqlite3 addon
LuaLS/LLS-Addons pull request #113
Opened 2024-02-04 11:59 UTC by KaitlynEthylia

Definition files for LuaSQLite3

https://lua.sqlite.org

2024-02-04 15:47 UTC, carsakiller requested changes
The submodule itself has not been committed. Please make sure you are using `git submodule add` to add the submodule and it is being committed, not just the changes to `.gitmodules`.

2024-02-05 16:38 UTC, carsakiller requested changes

2024-02-05 16:38 UTC, carsakiller commented on addons/lsqlite3/module
Please [run Stylua](https://github.com/LuaLS/LLS-Addons/blob/main/CONTRIBUTING.md#publishing-the-addon) to format the code and then push the updates.

2025-02-26 02:21 UTC, carsakiller commented
The StyLua requirement has been removed. Please let me know if the definitions are still up-to-date and if you would like this merged.

2025-02-27 23:44 UTC, KaitlynEthylia commented
luasqlite doesn't appear to have been updated since I first made this, so yes it's still up to date, but as I'm not using the library any more, I have very little interest in maintaining the addon should the library update and change its API

2025-02-28 03:43 UTC, carsakiller approved these changes
Going to go ahead with merging. If in the future this does need updating, hopefully someone will be able to carry the torch 🙂

2025-02-28 03:43 UTC, merged