Added libyue definitions
LuaLS/LLS-Addons pull request #37
Opened 2023-04-04 05:10 UTC by Frityet

(Libyue)[https://libyue.com] is a GUI library for C++, JS, and Lua. On the GitHub page, [there is a set of .json files which define the Yue API](https://github.com/yue/yue.github.io/tree/master/docs/latest/lua/api). The [`autogen.lua` file](https://github.com/Frityet/luayue-definitions/blob/master/autogen.lua) automatically turns that into CATS definitions.

2023-04-13 00:41 UTC, Frityet commented
> Hello 👋
> 
> Can you please create a separate branch that excludes the generation code and other unnecessary files and then update the submodule?

What do you mean by this?

2023-04-13 00:42 UTC, Frityet commented
> Any progress?

Just read this 😅

2023-04-13 00:55 UTC, carsakiller commented
There are a lot of files that should not be included as part of the addon
![image](https://user-images.githubusercontent.com/61925890/231617751-2d8f8edf-ff01-4ef4-9119-666ec659b934.png)
Also, the definitions must be in a “library” folder, so you will have to move the “yue” folder into a “library” folder. Check one of the already included addons to see what sort of structure is required.

2023-04-13 17:36 UTC, Frityet commented
> There are a lot of files that should not be included as part of the addon ![image](https://user-images.githubusercontent.com/61925890/231617751-2d8f8edf-ff01-4ef4-9119-666ec659b934.png) Also, the definitions must be in a “library” folder, so you will have to move the “yue” folder into a “library” folder. Check one of the already included addons to see what sort of structure is required.

Will do, thanks!

2023-04-13 17:38 UTC, Frityet commented
Done 👍

2023-04-13 18:32 UTC, carsakiller requested changes

2023-04-13 18:32 UTC, carsakiller commented on addons/yue/module
The submodule is still pointing to [`0768af`](https://github.com/Frityet/luayue-definitions/tree/0768af605a49667f8a959969d38befb661cae6f2). Please update it to point to the master branch where your changes have been made.

2023-04-13 18:32 UTC, carsakiller commented on addons/yue/module
The `yue` folder still needs to be moved into a `library/` directory as well.

2023-04-13 20:16 UTC, Frityet commented on addons/yue/module
Ah, thank you

2023-04-13 20:16 UTC, Frityet commented on addons/yue/module
Will do

2023-04-15 13:19 UTC, carsakiller commented
Please run [StyLua](https://github.com/JohnnyMorganz/StyLua) to apply the proper code style.

2023-04-16 23:25 UTC, Frityet commented
> Please run [StyLua](https://github.com/JohnnyMorganz/StyLua) to apply the proper code style.

Stylua fails because some argument names are also lua keywords, i.e `end`. Should I change this? It works fine on lualanguageserver

2023-04-17 03:26 UTC, Josef-Friedrich commented
How about https://github.com/JohnnyMorganz/StyLua#ignoring-parts-of-a-file ?

2023-04-19 21:30 UTC, Frityet commented
> How about [JohnnyMorganz/StyLua#ignoring-parts-of-a-file](https://github.com/JohnnyMorganz/StyLua#ignoring-parts-of-a-file) ?

im just gonna have automatic `keyword` -> `_keyword` so like, `end` would become `_end`

2023-04-22 00:07 UTC, carsakiller commented
Is using `end` not a syntax error? Any time I have mistakenly used `end`, I receive a syntax error.

2023-04-22 02:42 UTC, Frityet commented
> Is using `end` not a syntax error? Any time I have mistakenly used `end`, I receive a syntax error.

it is, however lua-language-server doesn't care for meta files

2023-04-22 02:51 UTC, Frityet commented
Anyways, fixed, im gonna make an API update and then push

2023-04-22 06:30 UTC, closed without merging