Update yue
LuaLS/LLS-Addons pull request #90
Opened 2023-09-18 03:06 UTC by Frityet

2023-09-22 17:50 UTC, carsakiller commented
@Frityet a check has failed

2023-09-25 19:03 UTC, Frityet commented
@carsakiller should fix it, its now one file instead of 100+

2023-09-26 03:36 UTC, carsakiller requested changes
Your branch is out of date and does not include some recent changes to LLS-Addons. Please update your branch and rebase your changes.

2023-09-26 03:36 UTC, carsakiller commented on addons/tex-luametatex/module
Please re-pull the latest changes that include the changes to this module.

2023-09-26 03:36 UTC, carsakiller commented on addons/tex-luatex/module
This module is also out of date in this PR.

2023-09-28 23:53 UTC, Frityet commented on addons/tex-luatex/module
whoops, thanks

2023-09-29 19:03 UTC, closed without merging