Update unbound api
LuaLS/LLS-Addons pull request #94
Opened 2023-10-21 22:13 UTC by Wolf-64

Updated API after some code-generator changes.

2023-10-23 06:11 UTC, carsakiller requested changes
I think this needs a rebase onto the main branch. You have 41 commits in the pull request (most of which are just from the main branch) and are modifying other addons (check modified files).

2023-10-23 16:10 UTC, carsakiller commented
@Wolf-64 please make sure that the files changed are what you expect. I rebased this PR on `LLS-Addons/main`.

The git history was pretty messed up with commits from other PRs, git merge conflict notices, commits that revert current changes to `LLS-Addons/main`, etc.

Please make sure when you are going to open a PR that you pull the latest changes from the upstream branch `LLS-Addons/main`. If your branch is outdated (has commits from before the latest to `LLS-Addons/main` and does not contain those new commits), please rebase it on `LLS-Addons/main` to get those latest commits and add your new ones on top. This makes things easier to read and more linear. I did this by checking out your branch and running `git rebase upstream/main -i` to open git's interactive rebase editor. I then dropped all the old commits and reworded your commit where you update the unbound API.

Merging `LLS-Addons/main` into your branch is also an option. but can lead to merge conflicts that you may find harder to deal with than rebasing.

2023-10-23 16:15 UTC, carsakiller approved these changes

2023-10-24 18:17 UTC, Wolf-64 commented
@carsakiller Thanks a bunch for resolving this on your end. 
I feel that what you're telling me now isn't really anything new to me at this point and I was pretty sure I've already did everything you said. I synched my fork and rebased the branch on main. This time I've used GitKraken to do this to make it a little lighter on myself and it reported that everything went well. Then checking later in the terminal it showed that it didn't go well at all, hence the small mess of commits and merges, which ultimately left me more confused. In the end it seemed fine, but I did indeed miss these two files of other addons that shouldn't have been in the changeset in the first place. 

I know it's not going to help anyone, but working with Subversion seems kind of a lot easier in this sense, so if it's a valid enough excuse, I'm not yet really used to this workflow. Anyway, thanks for pointing it out, here's hope the next time will be less messy, and thanks again.

2023-10-25 01:46 UTC, merged